#version 430 core
layout(local_size_x = 1, local_size_y = 1) in;

layout(binding = 0, rgba32f) writeonly uniform image2D output_image;
layout(binding = 1, rgba32f) readonly uniform image2D input_image;

uniform vec4 C;
uniform int max_iterations;
uniform float threshold;

void main()
{
	ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
	imageStore(output_image, pixel_coords, imageLoad(input_image, pixel_coords));
}